from django.urls import path
from team import views

urlpatterns = [
    path('create_base_team', views.create_base_team, name="create_base_team"),
    path('create_team', views.create_team, name="create_team"),
    path("get_all_tl_am_mgr", views.get_all_tl_am_mgr),
    path('get_all_team_name', views.get_all_team_name),
    path('get_all_base_team', views.get_all_base_team),
    path("get_team_hierarchy", views.get_team_hierarchy),
    path('get_all_emp', views.GetAllEmp.as_view(), name="get_all_employees"),
    path('get_all_inactive_emp', views.GetAllInactiveEmp.as_view(), name="get_all_inactive_emp"),
    path("get_employees_under_team", views.get_emp_under_team),
    path('get_my_team', views.GetMyTeam.as_view()),
    path("get_custom_my_team", views.get_custom_my_team),
    path('get_teams_under_manager', views.GetTeamsUnderManager.as_view(), name="get_teams_under_manager"),
    path("get_teams_list_under_manager/<str:emp_id>", views.get_teams_list_under_manager),
    path('get_emp', views.get_emp),
    path("get_all_teams", views.GetAllTeam.as_view(), name="get_all_teams"),
    path("get_my_team_list", views.GetMyTeamList.as_view(), name="get_my_team_list"),
    path("get_all_processes", views.GetAllProcess.as_view(), name="get_all_processes"),
    path("get_all_departments", views.GetAllDepartment.as_view(), name="get_all_departments"),
    path("get_all_designations", views.GetAllDesignation.as_view(), name="get_all_designations"),
    path("get_all_active_emp_ids", views.get_all_active_emp_ids),
    path("get_all_emp_ids", views.get_all_emp_ids, name="get_all_emp_ids_cc_team"),
    path("get_all_mapped_teams", views.GetAllMappedTeams.as_view(), name="get_all_mapped_teams"),
    path("replace_mapped_teams/<str:mapped_teams_id>", views.replace_mapped_teams,
         name="replace_mapped_teams_cc_team_only"),
    path("update_team_manager", views.update_team_manager, name="update_team_manager_cc_team_only"),
    path("update_my_team", views.update_my_team_api, name="update_my_team_cc_team_only"),
    path("get_all_replace_team_manager", views.GetAllReplaceTeamManager.as_view(),
         name="get_all_replace_team_manager_cc_team_only"),
    path("get_base_team_by_department", views.get_base_team_by_department),
]
