"""
Django settings for hrms project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path
from .pre_settings import *

import yaml

with open('hrms.yml', 'r') as f:
    yamldata = yaml.load(f, yaml.CLoader)

# mgmt,manager,agent,hr,ta
TEST_ACCOUNTS = yamldata.get('TEST_ACCOUNTS')
TEST_ACCOUNTS = [] if TEST_ACCOUNTS is None else TEST_ACCOUNTS.split(",")

SEND_EMAIL = yamldata.get('SEND_EMAIL', True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = yamldata.get('SEC_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = yamldata.get('DEBUG')
IS_PUBLIC_SERVER = yamldata.get("IS_PUBLIC_SERVER")
if IS_PUBLIC_SERVER:
    DEBUG = False

ALLOWED_HOSTS = yamldata.get('ALLOWED_HOSTS')
CSRF_TRUSTED_ORIGINS = yamldata.get('CSRF_TRUSTED_ORIGINS') or ["http://10.30.4.152:3000"]

# Application definition


CORS_ORIGIN_ALLOW_ALL = True
AUTH_USER_MODEL = 'mapping.Profile'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE += ('crum.CurrentRequestUserMiddleware',)

ROOT_URLCONF = 'hrms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'hrms.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
is_development = yamldata.get("DEVELOPMENT")
DB_HOST = yamldata.get("DB_HOST")
if DB_HOST is None:
    DB_HOST = "127.0.0.1"
if is_development:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': yamldata.get('DB_NAME') or 'HeyBobo_HRMSs',
            'USER': yamldata.get("DB_USER") or 'postgres',
            'PASSWORD': yamldata.get("DB_PASS") or 'Test@12345',
            'HOST': DB_HOST,
            'PORT': '5432',
        },
        'report': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'report.sqlite3',
        },

        # 'default': {
        #     'ENGINE': 'django.db.backends.sqlite3',
        #     'NAME': BASE_DIR / 'demo.sqlite3',
        # },
        # 'report': {
        #     # 'ENGINE': 'django.db.backends.sqlite3',
        #     # 'NAME': BASE_DIR / 'report.sqlite3',
        #     "ENGINE": "django.db.backends.mysql",
        #     'NAME': yamldata.get('REPORT_DB_NAME') or 'report',
        #     'USER': 'root',
        #     'PASSWORD': yamldata.get("REPORT_DB_PASS") or 'root',
        #     'HOST': DB_HOST,
        #     'PORT': '3306',
        # 
        # }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': yamldata.get('DB_NAME') or 'hrms',
            'USER': yamldata.get("DB_USER") or 'postgres',
            'PASSWORD': yamldata.get("DB_PASS") or 'postgres',
            'HOST': DB_HOST,
            'PORT': '5432',
        },
        'report': {
            # 'ENGINE': 'django.db.backends.sqlite3',
            # 'NAME': BASE_DIR / 'report.sqlite3',

            "ENGINE": "django.db.backends.mysql",
            'NAME': yamldata.get('REPORT_DB_NAME') or 'report',
            'USER': yamldata.get("REPORT_DB_USER") or 'root',
            'PASSWORD': yamldata.get("REPORT_DB_PASS") or 'root',
            'HOST': DB_HOST,
            'PORT': '3306',
        }

    }

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.TokenAuthentication',
        'utils.util_classes.CustomTokenAuthentication',
    ),
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_PAGINATION_CLASS': 'mapping.custom_pagination.CustomPagination',
    'PAGE_SIZE': 50
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not os.path.exists('log'):
    os.mkdir('log')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'server_logger': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 20,
            'filename': os.path.join(BASE_DIR, os.path.join('log', 'general.log')),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        '': {
            'handlers': ['server_logger'],
            'level': 'INFO',
            'propagate': True,
        },
    },

}

OPENAI_MODEL = "gpt-3.5-turbo"
OPENAI_API_KEY = yamldata.get("OPEN_API_KEY") or None

DEV_EMAIL_OTP_PATTERN = yamldata.get("DEV_EMAIL_OTP_PATTERN") or "@expertcallersdevtest.com"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
EMAIL_ACCOUNTS = yamldata.get("EMAIL_ACCOUNTS")

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtppro.zoho.com'
EMAIL_PORT = 587  # 465  # 587
EMAIL_HOST_USER = yamldata.get('EMAIL') or 'example123@expertcallers.com'
EMAIL_HOST_PASSWORD = yamldata.get('PASSWORD') or '12345'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ENABLE_QMS_INTEGRATION = True  # if is_development else False
ENABLE_QMS3_INTEGRATION = True
if is_development:
    QMS_URL = "http://0.0.0.0:8003"
    QMS3_URL = "http://0.0.0.0:9005"
else:
    QMS_URL = "https://qms.expertcallers.in"
    QMS3_URL = "https://qms.expertcallers.in"

# MIRAGE_SECRET_KEY = yamldata.get('MIRAGE_SECRET_KEY') or SECRET_KEY
# MIRAGE_CIPHER_IV = yamldata.get("MIRAGE_CIPHER_IV") or "1a2b3c4d5e6f7g8h"
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240  # higher than the count of fields
DATABASE_ROUTERS = (
    'report.dbrouters.ReportDBRouter',
)

ENABLE_TOTP = yamldata.get("ENABLE_TOTP", True)

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-article-token",  # Add your custom header here
]
from django.db import connection

DB_VENDOR = connection.vendor
